package:
  name: replicards
  version: "1.0.0"

source:
  path: ../

build:
  noarch: python
  script: python setup.py install
  # script: python setup_conda.py install

requirements:
  host:
    - python
    - setuptools
    - numpy
    - matplotlib
  run:
    - python
    - numpy
    - matplotlib

about:
  license: GNU GENERAL PUBLIC LICENSE
  summary: "An interactive way of teaching biological evolution through a card game."