---
title: "Material"
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3HLZHZMB0V"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-3HLZHZMB0V');
</script>


## Replicards

The *replicards* were $7 \times 7$ square grids (of size 7 cm $\times$ 7 cm), printed on thick paper. The **X** marks on the cells were drawn by the students using pencils.

We have made a [PDF file](images/PrintablePatterns.pdf) containing blank square grids and grids with the three different patterns to be printed if needed.

## Simulations

The code was written in *Python* and is available at [https://github.com/eliamascolo/replicards](https://github.com/eliamascolo/replicards).

Replicards package: [conda](https://anaconda.org/eliamascolo/replicards) or [pip](https://pypi.org/project/replicards/)

## Teacher slides

Suggested slides to present after the *Replicards* activity to contextualize and connect with biology the concepts “discovered” by the students during the activity. [[Slides](images/replicards_teachers_slides.pptx)]

